name: coffeebook
description: An innovative way to describe your coffee.
version: 1.0.0+1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  carousel_slider: ^1.3.0
  path_provider: ^1.6.5
  sqflite: ^1.3.0
  flutter_typeahead: ^1.4.0
  autocomplete_textfield: ^1.7.3
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  flutter_icons: ^1.0.0
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/kenya.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Bold.ttf
